from typing import Protocol, List
from src.models import Transaction

class ITransactionRepository(Protocol):
    """Contract for data persistence operations"""
    def add_transaction(self, transaction: Transaction) -> None: ...
    def get_all(self) -> List[Transaction]: ...
    def get_by_period(self, year: int, month: int) -> List[Transaction]: ...
    def delete_by_id(self, transaction_id: int) -> bool: ...

class IVisualizer(Protocol):
    """Contract for data visualization"""
    def generate_expense_pie_chart(self, transactions: List[Transaction], output_path: str) -> None: ...